name: Semantic-Release CI

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Get Next Version
        id: version
        run: |
          git fetch --tags
          echo "next=$(git tag | sort -r --version-sort | head -n1)" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v3
        with:
          repository: ernestojeda/test-e2e-testing
          ref: docker-release
          clean: true
          token: ${{ secrets.PROJECTS_PAT }}

      - name: Create docker-release
        env:
          RELEASE_YAML: release/rpc-go.yml
          NEXT_VERSION: ${{ steps.version.outputs.next }}
        run: |
          echo "Releasing rpc-go@$NEXT_VERSION"
          if [ "$NEXT_VERSION" != "" ]; then
            CURRENT_VERSION=$(sed -nre 's/(.*):v[0-9]*(([0-9]+\.)*[0-9]+).*/v\2/p' $RELEASE_YAML)
            sed -i "s/$CURRENT_VERSION/$NEXT_VERSION/g" $RELEASE_YAML
            echo "========================="
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git status
            git add .
            git commit -m "release(rpc-go): automated release of $NEXT_VERSION @ ${GITHUB_SHA::7}"
            git push origin docker-release
          fi